backend:
  name: github
  repo: omsaritainfotech-star/narayani-decor-site   # <— your repo
  branch: main
  base_url: https://api.netlify.com
  auth_endpoint: /auth
  use_graphql: true

media_folder: "public/uploads"
public_folder: "/uploads"

logo_url: "/images/logo.png"
site_url: "https://example.com"
collections:
  - name: pages
    label: Pages
    folder: content/pages
    create: true
    slug: "{{slug}}"
    format: frontmatter
    preview_path: "{{slug}}"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Slug, name: slug, widget: string, hint: "e.g. about" }
      - { label: Hero Image, name: hero_image, widget: image, required: false }
      - { label: Body, name: body, widget: markdown }
      - label: SEO
        name: seo
        widget: object
        required: false
        fields:
          - { label: Title, name: title, widget: string, required: false }
          - { label: Description, name: description, widget: text, required: false }
          - { label: OG Image, name: og_image, widget: image, required: false }

  - name: services
    label: Services
    folder: content/services
    create: true
    slug: "{{slug}}"
    format: frontmatter
    preview_path: "services/{{slug}}"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Slug, name: slug, widget: string }
      - { label: Excerpt, name: excerpt, widget: text, required: false }
      - { label: Hero Image, name: hero_image, widget: image, required: false }
      - { label: Body, name: body, widget: markdown }
      - label: SEO
        name: seo
        widget: object
        required: false
        fields:
          - { label: Title, name: title, widget: string, required: false }
          - { label: Description, name: description, widget: text, required: false }
          - { label: OG Image, name: og_image, widget: image, required: false }

  - name: products
    label: Products
    folder: content/products
    create: true
    slug: "{{slug}}"
    format: frontmatter
    preview_path: "products/{{slug}}"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Slug, name: slug, widget: string }
      - { label: Excerpt, name: excerpt, widget: text, required: false }
      - { label: Price (₹), name: price, widget: number, required: false, value_type: float }
      - label: Images
        name: images
        widget: list
        required: false
        field: { label: Image, name: image, widget: image }
      - { label: Body, name: body, widget: markdown }
      - label: SEO
        name: seo
        widget: object
        required: false
        fields:
          - { label: Title, name: title, widget: string, required: false }
          - { label: Description, name: description, widget: text, required: false }
          - { label: OG Image, name: og_image, widget: image, required: false }

  - name: projects
    label: Projects
    folder: content/projects
    create: true
    slug: "{{slug}}"
    format: frontmatter
    preview_path: "projects/{{slug}}"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Slug, name: slug, widget: string }
      - { label: Excerpt, name: excerpt, widget: text, required: false }
      - { label: Before Image, name: before_image, widget: image, required: false }
      - { label: After Image, name: after_image, widget: image, required: false }
      - { label: Body, name: body, widget: markdown }
      - label: SEO
        name: seo
        widget: object
        required: false
        fields:
          - { label: Title, name: title, widget: string, required: false }
          - { label: Description, name: description, widget: text, required: false }
          - { label: OG Image, name: og_image, widget: image, required: false }

  - name: testimonials
    label: Testimonials
    folder: content/testimonials
    create: true
    slug: "{{slug}}"
    format: frontmatter
    fields:
      - { label: Name, name: title, widget: string }
      - { label: Slug, name: slug, widget: string }
      - { label: Text, name: body, widget: markdown }

  - name: faqs
    label: FAQs
    folder: content/faqs
    create: true
    slug: "{{slug}}"
    format: frontmatter
    fields:
      - { label: Question, name: title, widget: string }
      - { label: Slug, name: slug, widget: string }
      - { label: Answer, name: body, widget: markdown }

  - name: settings
    label: Site Settings
    files:
      - file: content/settings/site.json
        label: Global Settings
        name: site
        format: json
        fields:
          - { label: Site Name, name: name, widget: string, required: false }
          - { label: Phone, name: phone, widget: string, required: false }
          - { label: WhatsApp, name: whatsapp, widget: string, required: false }
          - { label: Email, name: email, widget: string, required: false }
          - { label: Address, name: address, widget: text, required: false }
          - { label: Facebook, name: facebook, widget: string, required: false }
          - { label: Instagram, name: instagram, widget: string, required: false }
          - { label: Brand Primary, name: brand.primary, widget: string, required: false }
          - { label: Brand Accent, name: brand.accent, widget: string, required: false }
          - { label: Default SEO Title, name: seoDefault.title, widget: string, required: false }
          - { label: Default SEO Description, name: seoDefault.description, widget: text, required: false }
